### ISSUE TITLE
Use is_empty instead of empty

### ISSUE THREAD

**Issue by rickybassom** [openleap/leapong#1]
Since Leap Motion have changed the SDK, your program outputs:

Traceback (most recent call last):
  File "leapong.py", line 50, in on_frame
    if not frame.hands.empty and len(frame.hands) == 2:
  File "/usr/lib/python2.7/Leap.py", line 991, in <lambda>
    **getattr** = lambda self, name: _swig_getattr(self, HandList, name)
  File "/usr/lib/python2.7/Leap.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: empty

Changing empty to is_empty seems to solve the issue.

**Comment by astagi** [comment]
Thank you @Rickybas is fixed now :) hope to find the time to finish the project!
